version: '3.9'
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: db
    #    platform: linux/x86_64 #for m1 chip macs
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"      
      - "8025:8025"    
